### ISSUE TITLE
Tab Group Order Botched

### ISSUE THREAD

**Issue by iKlsR** [eggplanetio/tidytab#105]
Just tidied 30 something tabs, nothing happened so I thought TT was broken, checked releases, nothing new so hit CTRL SHIFT T a few times and tried again, same. Doing a search for one of my tabs I found a huge group of 60+ tabs (it tidied twice) but not at the top as I expect but way down in the middle.

![nani?! omae wa mou shindeiru](https://i.imgur.com/E5GqFMD.png)

If it helps I have about 600 tabs in my dash.

**Comment by briangonzalez** [comment]
I have noticed this as well, and will need some time to dig into the issue. Thanks @iKlsR !

**Comment by briangonzalez** [comment]
This only happens when you have it grouped by date, yes?

**Comment by iKlsR** [comment]
@briangonzalez Any time to look at this yet or an eta? No rush! :)  <sup><sup>but I'm dying over here</sup></sup>

**Comment by briangonzalez** [comment]
Haha, I'll find some time today :)

**Comment by briangonzalez** [comment]
I am fixing this now!!!!

**Comment by briangonzalez** [comment]
@iKlsR This has been fixed, but I need to wait on Google to do transfer ownership before I can release.

For now, you can grab it here and install it manually.

https://github.com/eggplanetio/tidytab/releases/tag/3.0.0

Cheers!

**Comment by briangonzalez** [comment]
@iKlsR We're live in the Google Chrome Store :)

**Comment by iKlsR** [comment]
Yay, I actually refreshed it last night. Why the long turnaround tho on G's
part

**Comment by briangonzalez** [comment]
I was transferring the extension from my eggplanet account to my personal and it takes 7 days  ¯\_(ツ)_/¯
