### ISSUE TITLE
Platform not supported

### ISSUE THREAD

**Issue by John0x** [eggplanetio/tidytab#23]
Hey, I've tried to test tidytab, but it doesn't work for me.

Dev console says:
``
chrome.clipboard is not supported on this platform or manifest version
``
Windows 10 64bit 
Chrome 57.0.2987.133 (64-bit)

**Comment by briangonzalez** [comment]
@John0x Thanks for the submission. We don't use `clipboard`, so I've removed it from the manifest and thus, you should no longer see this issue.

Can you upgrade an confirm? Thanks!

**Comment by John0x** [comment]
@briangonzalez upon clicking on the tidy tab I get:
````
popup.js:18 Uncaught (in promise) TypeError: Cannot read property 'children' of undefined
    at Object.<anonymous> (chrome-extension://lkglfdjcamhjoggmabobhggmpfjhccff/scripts/popup.js:18:12617)
    at o (chrome-extension://lkglfdjcamhjoggmabobhggmpfjhccff/scripts/popup.js:1:83807)
    at Generator._invoke (chrome-extension://lkglfdjcamhjoggmabobhggmpfjhccff/scripts/popup.js:1:84947)
    at Generator.t.(anonymous function) [as next] (chrome-extension://lkglfdjcamhjoggmabobhggmpfjhccff/scripts/popup.js:1:83986)
    at r (chrome-extension://lkglfdjcamhjoggmabobhggmpfjhccff/scripts/popup.js:18:10548)
    at chrome-extension://lkglfdjcamhjoggmabobhggmpfjhccff/scripts/popup.js:18:10642
````

**Comment by briangonzalez** [comment]
@John0x  What OS are you using?

**Comment by John0x** [comment]
@briangonzalez Windows 10 64bit

**Comment by briangonzalez** [comment]
2.0.0 just released and tested on both Mac / Windows! Can you give it a shot?

**Comment by John0x** [comment]
@briangonzalez still got the same error mentioned above.
I'm using chrome canary currently on windows 10 64bit.

**Comment by briangonzalez** [comment]
And you tried updating first?

**Comment by John0x** [comment]
@briangonzalez I have version: 2.2.0

**Comment by iKlsR** [comment]
Could this be an issue from using dev chrome? I'll check if I can repro this when I get home later.

**Comment by briangonzalez** [comment]
That would be great!

**Comment by iKlsR** [comment]
Ok, did an extensive test. Fresh canary install, no addons etc, latest win 10 x64, installed TT, first time I clicked *Tidy (n) tabs* it crashed the browser. Tried again, works as expected. Console has some interesting info however.

![](http://i.imgur.com/neCCtnZ.png)

**Comment by briangonzalez** [comment]
@John0x 

Do you have your browser in a  language other than english?

**Comment by John0x** [comment]
@briangonzalez My chrome is using the german language

**Comment by briangonzalez** [comment]
Ahhh, 2.6.0 should fix your issue then!

**Comment by John0x** [comment]
@briangonzalez ah, yeah, it does, thanks :)
