### ISSUE TITLE
What would it take to not use Other bookmarks?

### ISSUE THREAD

**Issue by iKlsR** [eggplanetio/tidytab#35]
OT doesn't use this and it's rather disconcerting to have it there, feels less "clean". Really not an issue but opening this for discussion anyways as I also have a specific set of folders at a certain length on my bookmarks bar, having the other bookmarks folder there cuts them off and gives me a dropdown.

**Comment by briangonzalez** [comment]
@iKlsR 

We can find a workaround. Can you send me a screenshot of your issue?

Thanks!

**Comment by iKlsR** [comment]
As I said, it's debatable if this really is an issue but was just entertaining the idea of not using the builtin bookmarks as storage. On my part, a little bit of OC since I don't use Other bookmarks folder at all, I keep a set of curated folders and having it there on the right cuts off my last folder to a dropdown. https://i.imgur.com/FZpxi7M.png

**Comment by briangonzalez** [comment]
Thanks for the screenshot. I originally had it using the default chrome storage but I found two issues there:

1. If you removed TidyTab, you'd lose all of your tabs unless you had _first backed up_. This bit me a few times.
2. When using bookmarks as storage, they magically appear in the Chrome omnibox suggestions upon typing. This is a neat added bonus.

**Comment by iKlsR** [comment]
> When using bookmarks as storage, they magically appear in the Chrome omnibox suggestions upon typing. This is a neat added bonus.

Agreed. I once cleared my cache with OneTab and lost some 200+ tabs. It was a nightmare to get back, had to search the data folder for the extension string and get a cached copy.

<strike>I'm not sure how far you want to take this project but I for one would gladly pay for cloud support -- a way to sync my tidied tabs across devices and be a more persistent form of storing these.</strike>

Actually... this is pretty great now that I'm noticing after loading up my other machine. My biggest gripe with OT was that I had different sessions across my several boxes, using the folder approach these can be synced! This is a deal winner for me.

**Comment by briangonzalez** [comment]
> using the folder approach these can be synced

Ohhhh, that's neat!

**Comment by briangonzalez** [comment]
One thing we could do is make the location we store the bookmarks configurable.

**Comment by iKlsR** [comment]
@briangonzalez That would be pretty good yes.
