### ISSUE TITLE
Prune timestamped folder as well for a deleted group

### ISSUE THREAD

**Issue by iKlsR** [eggplanetio/tidytab#36]
If I tidied a tab yesterday and then read it today and remove it, it gets removed from the dash but the now empty folder remains in Other bookmarks.

**Comment by iKlsR** [comment]
I did some digging and this is already being done. https://github.com/eggplanetio/tidytab/blob/master/lib/bookmark-manager.js#L48. Turns out it might be a weird side issue of the Other bookmarks being synced across machines. I can't quite reproduce it atm however.

**Comment by briangonzalez** [comment]
This happens when you remove an individual tab from a tabGroup and the group is now empty.

I am going to add in some code to prune empty tab groups when a tab is deleted.
