### ISSUE TITLE
Show url instead of title text in dashboard on hover

### ISSUE THREAD

**Issue by iKlsR** [eggplanetio/tidytab#37]
Showing the title on hover is redundant as it's what the link is saved as, maybe show the underlying url. This can help to jog one's memory as to what was there. Also some sites just use the site name so if I tidied two tabs from someone I would prefer to see `http://jdoe.com/vue_is_great` and `http://jdoe.com/chrome_is_ok` as opposed to `John Doe` `John Doe`.

**Comment by briangonzalez** [comment]
@iKlsR 

I've gone ahead and implemented your suggestion. Thanks for it!

<img width="1294" alt="screen shot 2017-04-13 at 10 46 11 am" src="https://cloud.githubusercontent.com/assets/659829/25016888/7b701628-2036-11e7-870c-05b0b3a63033.png">
