### ISSUE TITLE
Dark Theme Support

### ISSUE THREAD

**Issue by briangonzalez** [eggplanetio/tidytab#43]

**Comment by briangonzalez** [comment]
Closed via https://github.com/eggplanetio/tidytab/pull/42

**Comment by iKlsR** [comment]
Dark theme is not *dark*, expected contrasting colors, this bright purple is jarring! 😫 😄

**Comment by briangonzalez** [comment]
Adding in other theme called night so _you_ can pick your poison. Will come available in next release.

![screen shot 2017-04-18 at 7 37 15 am](https://cloud.githubusercontent.com/assets/659829/25136485/eba392cc-2409-11e7-8727-57279d88b70c.png)

**Comment by iKlsR** [comment]
@briangonzalez Looks great! You and these sweaters tho. 😁

**Comment by briangonzalez** [comment]
I guess I need to be careful about these screenshots, haha.

Prepping for a chili few weeks in Japan ;)
