### ISSUE TITLE
Tidying Current Tab Creates Unique Tab Groups

### ISSUE THREAD

**Issue by iKlsR** [eggplanetio/tidytab#48]
This looks like a bug. Have only tested tidying all tabs and tidying single tab. The latter creates new tab groups.

**Comment by iKlsR** [comment]
More testing, something is definitely broken. Behavior is inconsistent when tidying tabs, after removing from a group, the Tidy *n* tabs button also creates new groups.

**Comment by briangonzalez** [comment]
@iKlsR 

This seems expected. What's expected in your mind?

**Comment by iKlsR** [comment]
@briangonzalez I would expect all tidied tabs for a given range (day) to be under that new tab unless explicitly told not to. Tidying a current tab and having a new group seems excessive and can get out of hand quickly. 

Most of my issues come from using OT for 2 years now and I would think some people coming to this great oss project would have encountered it. This is my daily driver now but I think their "tab flow" is easier, moreso that they allow you to drag from group to group. 

My suggestions are either
1. Add documentation that explains this behavior *and or* a toggle to change it.
2. Allow moving tabs between groups.

**Comment by briangonzalez** [comment]
So the option would day something like?

```
When Tidying...

 [x] Create a new group for tabs
 [ ] Group tabs with the current day
```

@iKlsR

**Comment by iKlsR** [comment]
@briangonzalez Yes, sounds about right. If you're using the same wording I'd suggest "Group tabs by date added" for the latter* (and use UTC if not being done so already)*. Thanks!
