### ISSUE TITLE
Silently reject duplicates

### ISSUE THREAD

**Issue by iKlsR** [eggplanetio/tidytab#49]
A toggle to reject duplicates silently would be nice OR highlight them in a different color that signifies a dupe, <strike>current behavior is to split them into several tabs, not sure if this was a workaround of sorts. Also, is this behavior related to or a side product of https://github.com/eggplanetio/tidytab/commit/2c180f038642f5421dce633f774efe4980af643d?</strike> 

Struck out text is probably related to #48

**Comment by iKlsR** [comment]
@briangonzalez My js and vue are a bit rusty but I'd like to tackle this on the weekend. I might have a question or two!

**Comment by briangonzalez** [comment]
Awesome :) I can help.

All tabs run through this function, so you'll likely want to check for dups here and return false is current tab is a dup.

https://github.com/eggplanetio/tidytab/blob/a5f91622e3de2884be2e3061878e4fcbad091d24/lib/helpers.js#L22

**Comment by briangonzalez** [comment]
So right now, we don't tidy (a) pinned tabs or (b) tidy chrome extensions

**Comment by briangonzalez** [comment]
@iKlsR Doing ok?

**Comment by iKlsR** [comment]
@briangonzalez Work came up, I'll get to it tonight, thank for the pointer and the checkup! :)

**Comment by briangonzalez** [comment]
If you can't, that's totally ok, too :)

**Comment by iKlsR** [comment]
@briangonzalez Sorry for the afk, life came up and had to do a little surgery. Today def! :)

**Comment by iKlsR** [comment]
@briangonzalez Any idea what's going on here? https://gist.githubusercontent.com/anonymous/88644670d77a2c51d624826bef6c2b41/raw/0a71e3da4bfcb73f32de3c850fab05c7111dc339/dump.sh

**Comment by iKlsR** [comment]
@briangonzalez Sorry again for holding up this with what should have been a couple lines. I only have access to a windows box atm. 😢 

    npm ERR! Windows_NT 10.0.15063
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "dev"
    npm ERR! node v6.10.3
    npm ERR! npm  v3.10.10
    npm ERR! code EBADPLATFORM

    npm ERR! notsup Unsupported platform for inotify@1.4.1: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
    npm ERR! notsup Valid OS:    linux
    npm ERR! notsup Valid Arch:  any
    npm ERR! notsup Actual OS:   win32
    npm ERR! notsup Actual Arch: x64

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\iKlsR\Desktop\src\tidytab\npm-debug.log

**Comment by briangonzalez** [comment]
ruh roh, i got you!

**Comment by briangonzalez** [comment]
@iKlsR Should this look for dups across all previous tidied tabs?

**Comment by iKlsR** [comment]
@briangonzalez Yes.

**Comment by iKlsR** [comment]
@briangonzalez Yes, this should also be a toggle option that is off by default.

**Comment by briangonzalez** [comment]
@iKlsR I am slightly skeptical of the performance costs of this. We'll need to test it thoroughly.
