### ISSUE TITLE
TidyTab doesn't work on some computers

### ISSUE THREAD

**Issue by erenseymen** [eggplanetio/tidytab#52]
It simply cannot tidy the tabs. Video and log are attached.

OS: Windows 10 Pro 64-bit
Browser: Google Chrome 58.0.3029.81 (64-bit)
TidyTab version: 2.5.0

Note: It works fine on my Win7 x64 home computer.

[video and log.zip](https://github.com/eggplanetio/tidytab/files/946381/video.and.log.zip)

**Comment by briangonzalez** [comment]
@erenseymen Do you have a folder called "Other Bookmarks"in your bookmarks bar?

**Comment by erenseymen** [comment]
Yes, I have other bookmarks folder but its name is in Turkish language. ("Diğer yer işaretleri") Please see the attached screenshot.
![ss](https://cloud.githubusercontent.com/assets/27849007/25279925/ca4592fc-26b0-11e7-8e10-c8c8daa187ee.png)

Maybe the root cause is the language of Chrome. I'm having trouble with Turkish Chrome. My Chrome on my home computer is in English and TidyTab works fine.

**Comment by erenseymen** [comment]
By the way, is it possible to configure a custom folder for TidyTab? "Other Bookmarks" folder takes space on the bookmarks bar.

**Comment by erenseymen** [comment]
So, I've selected the language of Chrome as English and now it works OK. So problem occurs when the language is different than English I guess.

**Comment by briangonzalez** [comment]
@erenseymen I am about to publish version `2.6.0` with support for non-english languages. You can see the fix [here](https://github.com/eggplanetio/tidytab/pull/53).

**Comment by erenseymen** [comment]
Retested the issue with v2.6.0.

* Changed the language back to Turkish.
* TidyTab works fine.
* Verification PASSED.
* Thanks for the quick fix :)

**Comment by briangonzalez** [comment]
Wahoo!

I've added your feature request as an issue. You're not the only one asking for it, so when I have time, I'll make it happen :)

https://github.com/eggplanetio/tidytab/issues/54
