### ISSUE TITLE
Export Broken in 2.6.0

### ISSUE THREAD

**Issue by iKlsR** [eggplanetio/tidytab#55]
Nothing happens when trying to export.

![](http://i.imgur.com/FOHkCd9.png)

**Comment by briangonzalez** [comment]
Thanks @iKlsR 

Looks like it broke when I was cleaning up permissions. I'll send a patch later on today.

https://github.com/eggplanetio/tidytab/pull/51/files#diff-58c224c849582e7f9465c40fbd361c3dL55

**Comment by briangonzalez** [comment]
Also, sounds like it's about time for me to hook up a robust test suite:

https://github.com/eggplanetio/tidytab/issues/56

**Comment by briangonzalez** [comment]
Solved by https://github.com/eggplanetio/tidytab/pull/59
