### ISSUE TITLE
TidyTab Restores all Groups with Same Title

### ISSUE THREAD

**Issue by iKlsR** [eggplanetio/tidytab#57]
A couple of my extensions got corrupted just now so I had to delete my Chrome profile and connect it again. TidyTab restores all my groups but not in chronological order, they all have the same timestamp as the last group created.

Also sorry for ousting these before you can probably silently fix. 😁

**Comment by briangonzalez** [comment]
Yes, thanks for this. This is a known issue. I will look into solving it here shortly as well.

**Comment by iKlsR** [comment]
Haha, sorry for ousting these before you can sliently fix? but users man... gosh darn users! 😁

**Comment by briangonzalez** [comment]
No worries. Please to report when you find it, it'll help me stay organized.

One workaround is to just use the "bookmark manager" to export bookmarks the  re-import them later on. 

<img width="811" alt="screen shot on 2017-04-22 at 08-54-30" src="https://cloud.githubusercontent.com/assets/659829/25305969/8c864fe0-2739-11e7-940d-f92ebb24bd56.png">

**Comment by iKlsR** [comment]
@briangonzalez Ah, the bookmarks folder strikes again! I forgot and actually thought it was reading from local storage for some reason hence the "cached". Heh. This is pretty funny actually because after filing the export issue I deleted my profile and panicked a bit because I thought my 50+ tabs to read this weekend from this week were gone. Saved again, for OneTab you'd have to backup the `.localstorage-journal` file or everything would be gone.

**Comment by briangonzalez** [comment]
All Tidy does is take the current state of the world, JSON-stringify it, then offer it as a download. The state is always built by what's currently in your "TidyTab" bookmarks.

https://github.com/eggplanetio/tidytab/blob/16a5d3ccffa826da92a26430618af6e6eaf7e51f/app/component/export.vue#L13-L17

Hope this helps!

**Comment by iKlsR** [comment]
Finally got back on my linux box to do some work today and I fired up TidyTab only too see that it now has every group as the same `Sun 06/4 @ 7:48pm` which was my last Tidy this evening on Windows.

**Comment by briangonzalez** [comment]
Eh? Mind screenshotting for me?

**Comment by iKlsR** [comment]
It should look like this as it does on my Windows machine now.

![](http://i.imgur.com/fuoPQ7L.png)

Instead, imagine everything under the `Sunday 06/04`, the entry at the top but saying `19 Tabs Sunday 06/04`, it just groups everything under the most recent date. If I switch the filter to `by tidy` it's the same, everything is grouped together. I think you might be able to reproduce this by installing TT on a fresh chrome in a VM and syncing bookmarks.

**Comment by briangonzalez** [comment]
Well, I see it now too on a canary chrome. This is frustrating because `chrome.bookmarks` is reporting the `dateAdded` incorrectly as the day they were imported into the new chrome instance.

I guess I could always fall back to the title of the folder, which is the timestamp, it's just much uglier. Sigh.
