### ISSUE TITLE
Build options UI

### ISSUE THREAD

**Issue by briangonzalez** [eggplanetio/tidytab#58]
https://developer.chrome.com/extensions/optionsV2

**Comment by briangonzalez** [comment]
@iKlsR

Would love a hand looking over the copy on the options page I've just created. Thanks!

![screen shot 2017-04-23 at 3 18 57 pm](https://cloud.githubusercontent.com/assets/659829/25317946/b106b51c-2838-11e7-9f76-8b28b30b190c.png)

**Comment by briangonzalez** [comment]
Will likely go with something like this as an MVP.

![screen shot 2017-04-23 at 5 02 26 pm](https://cloud.githubusercontent.com/assets/659829/25318571/b2a16fa8-2846-11e7-9edd-79f0c145bc73.png)

**Comment by iKlsR** [comment]
@briangonzalez Nice! I really like the first version. I'm not sure what the Tab Storage section in the second iteration is implying initially. The common issue I see across both is finding a way to express how one can change the storage directory clearly.

**Comment by iKlsR** [comment]
I'd say the first version is very good but for the *Tab Storage* section. How about 

*[ verbatim explanation ]*

To change this location, specify a location in the format `Bookmarks Bar -> My Folder | TidyTab`, if this location does not exist it will be created. Your tidied tabs will be grouped according to their tab group. 

Needs a little fine tuning but trying to mix the tone of both into one simple block.
