### ISSUE TITLE
Custom Tab Group Titles

### ISSUE THREAD

**Issue by iKlsR** [eggplanetio/tidytab#60]
Having the option to change the title of the tab group would be useful. Often before tackling some bit of work I like to do some research and can amass a great number of tabs, would be nice to tidy these for reference later and then tag this group as `Some Topic Research` etc.

Having this and some underlying identifiable structure would then allow us to have the tabs saved as bookmarks with reasonable names as opposed to `1492096347274`.

**Comment by briangonzalez** [comment]
@iKlsR How would naming work when a user chooses to "Group by Date"?

I have some ideas, but want to hear your thoughts.

**Comment by iKlsR** [comment]
@briangonzalez That sounds perfect, that's what I would go with.

**Comment by iKlsR** [comment]
@briangonzalez Actually, grouping by date now kinda negates the need for this. For this issue to be useful one would also need the functionality to move tabs from one group to another.
