### ISSUE TITLE
Cannot Remove Tidied Tab

### ISSUE THREAD

**Issue by iKlsR** [eggplanetio/tidytab#61]
Trying to remove a url from a group. Nothing happening. Console...

![](http://i.imgur.com/J7Qmzr5.png)

Could this be a side effect of #57? I don't have the luxury of testing it atm.

**Comment by iKlsR** [comment]
Yes, it is a product of #57

**Comment by briangonzalez** [comment]
@iKlsR Would you be willing to send me your export?

**Comment by briangonzalez** [comment]
@iKlsR Also, would you be will to screenshot your `TidyTab` folder?

**Comment by iKlsR** [comment]
@briangonzalez Oops, forgot about this! I have 3 groups and they all have the same title as the last added one.

![](http://i.imgur.com/aR5PJiW.png)

Bookmarks folder has unique names but still

![](http://i.imgur.com/jHySxZZ.png)

**Comment by briangonzalez** [comment]
Is this still an issue @iKlsR ?

**Comment by iKlsR** [comment]
@briangonzalez Yes.

**Comment by briangonzalez** [comment]
Hmm, I wonder how they got the same timestamp...
