### ISSUE TITLE
Any Love for Users with Darker Themed Chrome?

### ISSUE THREAD

**Issue by iKlsR** [eggplanetio/tidytab#62]
![](http://i.imgur.com/DkPt26p.png)

Could probably go for a more *agnostic?* look with lighter purple or a [sticker look](https://www.one-tab.com/web/images/home/large-funnel.png) with a [white back and thick border](https://github.myshopify.com/products/octodex-sticker-packs).

**Comment by briangonzalez** [comment]
Yes, I want this too! We'll find a workaround :)

**Comment by briangonzalez** [comment]
Fixed by #66 – release forthcoming.
