### ISSUE TITLE
A keyboard shortcut for quickly tidying all tabs (all windows) and opening a new tab

### ISSUE THREAD

**Issue by erenseymen** [eggplanetio/tidytab#65]
... would be great.

[PanicButton](https://chrome.google.com/webstore/detail/panicbutton/faminaibgiklngmfpfbhmokfmnglamcm) extension does this with F4 key and F4 is a great choice for this kind of shortcut.

Note: This shortcut shouldn't open TidyTab dashboard because it's a panic situation :)

**Comment by briangonzalez** [comment]
I want this too and will be adding it very soon.

**Comment by briangonzalez** [comment]
Once `2.9.0`  lands in the chrome store in about an hour, this will be possible via a double-keypress of <kbd>Alt</kbd>+<kbd>t</kbd>.

I have plans to make this configurable in the near future.

**Comment by briangonzalez** [comment]
See demo here: http://d.pr/v/u5NJk

**Comment by iKlsR** [comment]
@briangonzalez Random.. http://hckrnews.com is a much nicer interface to browse, it comes timestamped and nice filters, also it groups stuff you might have missed from last visited.
