### ISSUE TITLE
Dashboard being pinned can be annoying

### ISSUE THREAD

**Issue by erenseymen** [eggplanetio/tidytab#67]
There is a problem about pinned dashboard. I think it's bug. Let me explain.
1) There are 2 open tabs, one is pinned Tidy dashboard, the other is a regular empty tab.
2) Close pinned dashboard
3) Close the last tab
4) Open Chrome again
* Pinned dashboard sometimes comes up and sometimes doesn't. I don't know what to expect here. Maybe it's a Chrome sync bug, not sure about that.

My suggestion is abondoning pinned dashboard completely or making it optional.

I think the behaviour when tidying all tabs should be like this:
1) If there is no other window, then open a new tab.
2) If there are other window(s), open nothing.
3) If panic button is pressed, tidy all windows and close Chrome. ( #65 previously requested feature)

This way, user can start a new project (or a new chapter in the life of procrastination) instantly with a new tab without being bothered by the dashboard. I know it looks cool all the tabs closing and the dashboard opening instantly but usability comes first in my opinion.

Moreover I never use pinned tabs on Chrome and don't like them anyway. I'm sure there are a lot of people like me.

**Comment by iKlsR** [comment]
> Pinned dashboard sometimes comes up and sometimes doesn't. I don't know what to expect here. Maybe it's a Chrome sync bug, not sure about that.

I've gotten something like that, it also happens when the extension gets updated.

> Moreover I never use pinned tabs on Chrome and don't like them anyway. I'm sure there are a lot of people like me.

Disagree. It's a nice way to keep it out of the way unless needed.

The rest is up for debate.

**Comment by iKlsR** [comment]
@briangonzalez Side note, maybe some labels are in order for tagging these?

**Comment by briangonzalez** [comment]
I love the way you think @erenseymen. Usability is key, not just for me or @iKlsR.

I think a simple option like so could serve us well and make us all happy:

```
After Tidying:

- [ ] Open the TidyTab dashboard
- [ ] Do nothing (a new tab will be created if all tabs have been closed)
```

**Comment by briangonzalez** [comment]
@iKlsR Labels = great idea.

I've added you as a collaborator, so feel free to help triage and add labels as you see fit :)

**Comment by iKlsR** [comment]
@briangonzalez Thanks, omw home now. Will check rest of notifications later!

**Comment by briangonzalez** [comment]
@erenseymen This has been added in in `2.10.0-beta.1`. Mind testing it out here? Thanks. 

https://github.com/eggplanetio/tidytab/releases/tag/2.10.0

**Comment by erenseymen** [comment]
@briangonzalez Loaded 2.10.0 but it doesn't work. Screenshots attached. Am I doing something wrong?
![no options](https://cloud.githubusercontent.com/assets/27849007/26005283/441c95ee-3741-11e7-8abc-6831e76bf6a6.png)
![no tidy](https://cloud.githubusercontent.com/assets/27849007/26005282/441bbc5a-3741-11e7-9a87-92fbb62e92ac.png)

**Comment by briangonzalez** [comment]
Ahh, I think I forgot to attach the zip to the release. I've attached it now. You'll need to download the correct package and go through those steps once more. Thanks :)

http://d.pr/i/1RhGb

**Comment by iKlsR** [comment]
@briangonzalez is [a mess](https://www.youtube.com/watch?v=H6YIcblXky4). 😁

**Comment by briangonzalez** [comment]
Fixed in 2.10.0 which is live.

**Comment by erenseymen** [comment]
minor bug. option should be selected by default.
![minor](https://cloud.githubusercontent.com/assets/27849007/26080255/f9850cdc-39c5-11e7-802d-6492827a178d.png)

**Comment by briangonzalez** [comment]
Great find, thanks @erenseymen – hopefully the rest worked for you.

**Comment by erenseymen** [comment]
Yes, thanks.
