### ISSUE TITLE
Force bookmark sync (if possible) after tidying

### ISSUE THREAD

**Issue by erenseymen** [eggplanetio/tidytab#68]
Title says it all.

**Comment by iKlsR** [comment]
@erenseymen  What do you mean? Isn't this automagically handled by Chrome immediately or am I misunderstanding?

**Comment by erenseymen** [comment]
@iKlsR Unfortunately it's not reliable. You need to wait a little while for Chrome to sync before closing Chrome.

**Comment by briangonzalez** [comment]
@erenseymen I don't think I (as a developer) have control over the sync interval. If you can show me documentation that shows otherwise (and how), I'd be happy to add it in.

**Comment by briangonzalez** [comment]
Here are the docs I am going off of:

https://developer.chrome.com/extensions/bookmarks

**Comment by briangonzalez** [comment]
Going to close for now. We can reopen once/if we find something.

**Comment by iKlsR** [comment]
It could be a quirky hack as per https://superuser.com/a/385605 but unless there is overwhelming call for this I don't think it's necessary really.

**Comment by erenseymen** [comment]
@iKlsR @briangonzalez Is it possible to use storage and force the storage to sync? https://developer.chrome.com/extensions/storage
