### ISSUE TITLE
Links in Tab Group Color On Focus and Off Focus

### ISSUE THREAD

**Issue by sifxtreme** [eggplanetio/tidytab#75]
In a previous iteration of Tidy, the links in a Tab Group would brighten up if your mouse focused on the tab group and dim down on off-focus. 

Can we bring this feature back?

**Comment by sifxtreme** [comment]
Personal pref is for this commit => 14238aae3bd50636ed09d12262f17498736124d7

**Comment by briangonzalez** [comment]
Fixed in 2.12.1
