### ISSUE TITLE
There are no time info in the group titles of the "Group by Tidy" view

### ISSUE THREAD

**Issue by erenseymen** [eggplanetio/tidytab#80]
... and "Group by Day" view has time info in the group titles. This should be the opposite way.

![bytidy](https://cloud.githubusercontent.com/assets/27849007/26320280/fbe9617a-3f2a-11e7-8a16-96fee3d223f5.png)
![bydate](https://cloud.githubusercontent.com/assets/27849007/26320354/44dd6110-3f2b-11e7-9e34-267edb62718c.png)

**Comment by briangonzalez** [comment]
Whoops, good catch. I'll push a fix later tonight.
