### ISSUE TITLE
There is no remove option in the "Group by Day" view

### ISSUE THREAD

**Issue by erenseymen** [eggplanetio/tidytab#81]
![bydate](https://cloud.githubusercontent.com/assets/27849007/26320436/8db8214a-3f2b-11e7-8e9a-81a74c1fcf10.png)

**Comment by briangonzalez** [comment]
@erenseymen 

What would you expect to happen here? Remove all of the tidys for that day? I was afraid that was to destructive.

**Comment by erenseymen** [comment]
Maybe a confirmation message like "You are about to remove all the tab groups in this day. Are you sure?" would be the best way.
