### ISSUE TITLE
Bookmark folder selection menu is missing

### ISSUE THREAD

**Issue by erenseymen** [eggplanetio/tidytab#86]
In the options under "Tab Storage", custom folder selection menu is missing.

Tidy version 2.15.0

![image](https://cloud.githubusercontent.com/assets/27849007/26532766/f21dd67a-4412-11e7-8bd7-793982bd30de.png)

**Comment by briangonzalez** [comment]
@erenseymen Good catch. I accidentally cleaned up too much when I was fixing lint warnings.

Thanks!
