### ISSUE TITLE
Export groups to file

### ISSUE THREAD

**Issue by iKlsR** [eggplanetio/tidytab#98]
Often after an intense research session (imagine dozens of tabs), I like to save these to a file somewhere in my Dropbox I can retrieve later if needed. No need to be able to import these back, I just don't want to pollute my bookmarks or bog down TT with stuff I don't immediately need or might never need later. 

Not a crucial must have, just wrapping my daily workflow around this tool but at the same time I think it's also beneficial to have grouped selective export as well instead of dumping the whole tree.

**Comment by iKlsR** [comment]
Other side note, `2.22 - 3` would be pretty stable and feature filled enough to do another round on hn, rdt.

**Comment by briangonzalez** [comment]
@iKlsR 

Nice, yeah. I was thinking about doing another push as well. Though I first wanted to redesign the logo and other chrome store assets.

**Comment by mikhoul** [comment]
I second for Export too but having also an Import for future use or baqck-up purpose would be really useful. 

Thanks for this addon :octocat:

**Comment by briangonzalez** [comment]
@mikhoul have you tried the import/export we have currently?

**Comment by briangonzalez** [comment]
<img width="955" alt="screen shot 2017-06-30 at 14 03 57" src="https://user-images.githubusercontent.com/659829/27758815-0ac214be-5dd3-11e7-80c6-93b6187b910d.png">

**Comment by mikhoul** [comment]
Thanks 👍

**Comment by yowainwright** [comment]
@briangonzalez @mikhoul does the response above mean this issue can be resolved?

**Comment by briangonzalez** [comment]
I think so :)
