### ISSUE TITLE
Difficulty with multiple windows

### ISSUE THREAD

**Issue by chialynn** [eggplanetio/tidytab#99]
When I have more than one window open, TidyTab seems to have trouble figuring out which one I want to tidy. 

Example: Window one has six tabs open. Window two has four. In window one, I click "tidy 6 tabs." Nothing appears to happen. However, when I open the dashboard, I find the four tabs from window two. Similarly, if I click "tidy all but the current tab," I find all but one of the tabs from the other window.

ETA: Chrome 59.0.3071.115, OSX 10.12.5.

**Comment by briangonzalez** [comment]
Thanks for the report @chialynn.

I presume [this bit of code](https://github.com/eggplanetio/tidytab/blob/master/lib/helpers.js#L57) is picking up the window that the background script is running in, not necessarily the frontmost window.

I'll dig in this week!

**Comment by briangonzalez** [comment]
Fixed: https://chrome.google.com/webstore/detail/tidytab/lkglfdjcamhjoggmabobhggmpfjhccff?authuser=1

**Comment by chialynn** [comment]
That was fast! Thanks!

**Comment by briangonzalez** [comment]
@chialynn Have you had a chance to try it out? Did it work for you?

**Comment by sifxtreme** [comment]
Oh snaps! I've had this problem too!

**Comment by chialynn** [comment]
I just tried it out—seems to be working!
